language: go
os:
  - 'linux'
  - 'osx'
sudo: false
go:
  - '1.10'
  - '1.11'
  - 'tip'
install:
  - 'cd ${TRAVIS_HOME}/gopath'
  - 'go get -u golang.org/x/vgo'
  - 'mkdir $HOME/test'
  - 'rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/test/'
  - 'cd $HOME/test'
script: 'if [ $(go version | awk "{print $3}") == go1.10 ]; then vgo test -v -race -count=10; else go test -v -race -count=10; fi'
